# -*- coding: utf-8 -*-
"""create_script_script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YUL57gc54uWep2nCcqI6YXh60x6hzhbq
"""

import csv
import pandas as pd
from collections import defaultdict
import json
import requests

train_data_csv_url = "https://raw.githubusercontent.com/forrestpark/AtypicalSpeech/master/data/train_data.csv"
test_data_csv_url = "https://raw.githubusercontent.com/forrestpark/AtypicalSpeech/master/data/test_data.csv"
valid_data_csv_url = "https://raw.githubusercontent.com/forrestpark/AtypicalSpeech/master/data/valid_data.csv"

train_data = pd.read_csv(train_data_csv_url)
test_data = pd.read_csv(test_data_csv_url)
valid_data = pd.read_csv(valid_data_csv_url)

scriptID2utterances = defaultdict(list)
scriptID2utteranceDetails = defaultdict(list)

for data in [train_data, test_data, valid_data]:
  for index, row in data.iterrows():
    scriptID = row['speakerId']
    # print("script id: ", scriptID)

    utterance = row['transcription']

    details = {"action": row['action'], "object": row['object'], "location": row['location']}
    # print("details: ", details)

    scriptID2utterances[scriptID].append(utterance)
    scriptID2utteranceDetails[scriptID].append(details)
   
for scriptID, utterance in scriptID2utterances.items():
  scriptID2utterances[scriptID].insert(0, "")
  scriptID2utteranceDetails[scriptID].insert(0, dict())

# print(len(scriptID2utterances["2BqVo8kVB2Skwgyb"]))
# print(len(scriptID2utteranceDetails["2BqVo8kVB2Skwgyb"]))

update_script_url = "/api/script/update_script"

for scriptID, utterances in scriptID2utterances.items():
  request_data = json.dumps({"script_id": scriptID, "utterances": {"utterances": utterances, "details": scriptID2utteranceDetails[scriptID]}})
  res = requests.put(update_script_url, data=request_data, headers={"Content-Type": "application/json"})
  print(res.json())